kind: Template
apiVersion: v1
metadata:
  name: egressproxy-template
objects:

- kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: egressproxy-${NAME}
      egressproxy: "true"
    name: egressproxy-${NAME}
  spec:
    ports:
    - name: 3128-tcp
      port: 3128
      protocol: TCP
      targetPort: 3128
    selector:
      app: egressproxy-${NAME}
    sessionAffinity: None
    type: ClusterIP

#### egressproxy-${NAME}-a ####

- kind: ConfigMap
  apiVersion: v1
  data:
    list.txt: |
      .basefarm.com
  metadata:
    name: egressproxy-${NAME}-a-allow-policy
    labels:
      egressproxy: "true"
      egressproxy-allow-policy: "true"
      app: egressproxy-${NAME}
      deploymentconfig: egressproxy-${NAME}-a

- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    labels:
      app: egressproxy-${NAME}
      egressproxy: "true"
      deploymentconfig: egressproxy-${NAME}-a
    name: egressproxy-${NAME}-a
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: egressproxy-${NAME}
      egressproxy: "true"
      deploymentconfig: egressproxy-${NAME}-a
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: egressproxy-${NAME}
          egressproxy: "true"
          deploymentconfig: egressproxy-${NAME}-a
      spec:
        containers:
        - name: egressproxy-${NAME}-a
          env:
          - name: SQUID_CACHE_MGR_MAIL
            value: support@basefarm.com
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3128
            timeoutSeconds: 1
          imagePullPolicy: Always
          ports:
          - containerPort: 3128
            protocol: TCP
          resources:
            limits:
              cpu: 150m
              memory: 96Mi
            requests:
              cpu: 50m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/squid/allow-custom-domains
            name: egressproxy-allow-policy
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - egressproxy-${NAME}
                topologyKey: kubernetes.io/hostname
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 45
        volumes:
        - configMap:
            defaultMode: 420
            name: egressproxy-${NAME}-a-allow-policy
          name: egressproxy-allow-policy 
    test: false
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - egressproxy-${NAME}-a
        from:
          kind: ImageStreamTag
          name: ${IMAGESTREAM_NAME}:${IMAGE_TAG}
          namespace: ${IMAGESTREAM_NAMESPACE}

#### egressproxy-${NAME}-b ####

- kind: ConfigMap
  apiVersion: v1
  data:
    list.txt: |
      .basefarm.com
  metadata:
    name: egressproxy-${NAME}-b-allow-policy
    labels:
      egressproxy: "true"
      egressproxy-allow-policy: "true"
      app: egressproxy-${NAME}
      deploymentconfig: egressproxy-${NAME}-b

- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    labels:
      app: egressproxy-${NAME}
      egressproxy: "true"
      deploymentconfig: egressproxy-${NAME}-b
    name: egressproxy-${NAME}-b
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: egressproxy-${NAME}
      egressproxy: "true"
      deploymentconfig: egressproxy-${NAME}-b
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: egressproxy-${NAME}
          egressproxy: "true"
          deploymentconfig: egressproxy-${NAME}-b
      spec:
        containers:
        - name: egressproxy-${NAME}-b
          env:
          - name: SQUID_CACHE_MGR_MAIL
            value: support@basefarm.com
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3128
            timeoutSeconds: 1
          imagePullPolicy: Always
          ports:
          - containerPort: 3128
            protocol: TCP
          resources:
            limits:
              cpu: 150m
              memory: 96Mi
            requests:
              cpu: 50m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/squid/allow-custom-domains
            name: egressproxy-allow-policy
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - egressproxy-${NAME}
                topologyKey: kubernetes.io/hostname
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 45
        volumes:
        - configMap:
            defaultMode: 420
            name: egressproxy-${NAME}-a-allow-policy
          name: egressproxy-allow-policy 
    test: false
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - egressproxy-${NAME}-b
        from:
          kind: ImageStreamTag
          name: ${IMAGESTREAM_NAME}:${IMAGE_TAG}
          namespace: ${IMAGESTREAM_NAMESPACE}

parameters:
- name: NAME
  value: "default"
  required: true
- name: IMAGESTREAM_NAME
  value: bf-squid
  required: true
- name: IMAGESTREAM_NAMESPACE
  value: openshift
  required: true
- name: IMAGE_TAG
  value: latest
  required: true
